### ISSUE TITLE
Add chef_search capabilities to server nodes

### ISSUE THREAD

**Issue by fernandohonig** [johnbellone/consul-cookbook#106]
Currently there is no way to bootstrap a full cluster without creating the nodes first and update the ['consul']['servers'] array with the list of IPs.

I can work in some recipe to tag the nodes and use that tag to make a chef_search and when reached the number of servers needed, bootstrap the cluster.

**Comment by isuftin** [comment]
:+1: This would be useful. Im trying to figure out how I would do that today if I know I plan on having 3, 5, etc servers up

**Comment by fernandohonig** [comment]
Could be something like this. Make any comments please.

tag('consul_cluster') if node[consul][service_mode] == 'cluster'

nodes = search('node', 'tags:consul_cluster')
	Chef::Log.debug("Found consul nodes at #{nodes.join(', ').inspect}")
node.set['consul']['servers'] = nodes.join(',')

if node['consul']['servers'].to_i >= node['consul']['bootstrap_expect']
	 node.set['consul']['retry_on_join'] = true
end

**Comment by isuftin** [comment]
@fernandohonig I'd really appreciate something like that. The workflow I'm dealing with right now just doesn't work in an automated fashion. Im trying to cluster 3 servers and I already know what their addresses will be, but if I have the default['consul']['servers'] attribute set when provisioning the machines, they fail to come up. I have a ticket open [here](https://github.com/johnbellone/consul-cookbook/issues/107) for that. 

I'm fairly new to Chef. Would your solution fix my problem and allow me to launch 3 machines at once to be clusters without any further hand-configuration? 

I was hoping to accomplish something like this in my Vagrantfile:

    (1..3).each do |i|
        config.vm.define "cluster-#{i}", primary: true do |node|
          node.vm.network "private_network", ip: "10.0.0.1#{i}"
          node.vm.provision :chef_solo do |chef|
            chef.add_recipe "consul::default"
            chef.json.merge!({
                :consul => {
                  "servers" => ["10.0.0.10","10.0.0.11","10.0.0.12"],
                  "service_mode" => "cluster"
                }
              })
            end
        end
      end

**Comment by isuftin** [comment]
@fernandohonig Actually, now that I thought about it, is this necessary? Consul clusters will learn about one another when they connect. I've had luck with the following: 


    (1..3).each do |i|
    config.vm.define "cluster-#{i}", primary: true do |node|
      node.vm.network "private_network", ip: "10.0.0.1#{i}"
      node.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = "256"
      end
      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", "256"]
      end
      node.vm.provision :chef_solo do |chef|
        chef.add_recipe "consul::default"
        chef.json.merge!({
            :consul => {
              "servers" => ["10.0.0.11"],
              "service_mode" => "cluster",
              "bootstrap_expect" => "3",
              "retry_on_join" => true,
              "enable_syslog" => true,
              "log_level" => "debug",
              "node_name" => "cluster-#{i}",
              "advertise_addr" => "10.0.0.1#{i}",
              "bind_interface" => "eth1",
              "advertise_interface" => "eth1"
            }
          })
        end
    end
  end


What ends up happening is that the first cluster node comes up and waits. The second cluster node comes up and connects to the first. Now the first and second know about both. The third node comes up and connects to the first and now all the nodes know about one another.

Because of this, do we need to then re-initialize these clusters with more servers? They should know about every other server in the network via gossip, correct?

**Comment by johnbellone** [comment]
I am not a fan of using search as a means of orchestration. A few months back I [put an example of using chef-provisioning](https://github.com/johnbellone/consul-cookbook/blob/master/cluster.rb) to bootstrap a cluster. Let me think about this a little more.

**Comment by johnbellone** [comment]
I am closing this out because of impeding #126 landing on master. This can be added as a pull-request to the new branch. It should be a separate recipe which overrides the servers configuration attribute.
