### ISSUE TITLE
install_binary breaks upgrade

### ISSUE THREAD

**Issue by akerekes** [johnbellone/consul-cookbook#116]
The file resource in install_binary which is intended to change the permissions of the installed binary also changes the mod_date of the executable to the current date. E.g.: if I install an older version of consul in 2014 December, which has mod_date of 2014 August, the file resource will change the mod_date to 2014 December. Now if I want to install a newer version that was released e.g in 2014 November, the unzip step of the ark resource will not overwrite the older version executable as it has newer mod_date than the newer version (2014 Dec vs 2014 Nov).

**Comment by reset** [comment]
@akerekes thanks for the report. This is fixed in https://github.com/johnbellone/consul-cookbook/pull/121
