### ISSUE TITLE
Purpose yum-repoforge?

### ISSUE THREAD

**Issue by jhmartin** [johnbellone/consul-cookbook#120]
What is the purpose of this dependency? It appears to only be referenced in the Kitchen configuration. Including this forces Yum 3.0 cookbook in the dependency tree, which is difficult to migrate to from 2.0 in a large installation.

**Comment by johnbellone** [comment]
Purpose was for EL5 compilation. I don't have any problems removing it.

**Comment by johnbellone** [comment]
I'll take a look at doing this later. Its probably time we put a bullet in EL5 support.
