### ISSUE TITLE
Databag item 'ca_file' misnamed

### ISSUE THREAD

**Issue by jhmartin** [johnbellone/consul-cookbook#124]
The documentation indicates that a databag item with the key 'ca_file' will become the contents of /etc/consul.d/ca.pem, however the key actually needs to be 'ca_cert'.

**Comment by logankoester** [comment]
This is also true of the `['consul']['ca_file']` attribute. Using `['consul']['ca_cert']` does populate the expected file, as in your case.

**Comment by johnbellone** [comment]
I am closing this out because of impeding #126 landing on master.
