### ISSUE TITLE
Sensitivity to HUP during launch

### ISSUE THREAD

**Issue by jhmartin** [johnbellone/consul-cookbook#125]
The consul agent is sensitive to a HUP during its initialization process, such as when invoked via 'knife ssh'.  Adding a nohup to the invocation or adding a sleep after it seems to clear up the issue.

I've opened an issue against consul itself as well.

**Comment by johnbellone** [comment]
I'm not sure if this is a recipe bug or something due to underlying service. It sounds like we should wait to hear back from the project. Do you have a link to the issue?

**Comment by jhmartin** [comment]
Heard back from HashiCorp: https://github.com/hashicorp/consul/issues/677 .  They say the HUP is coming in before the signal handler is installed, and the init script should add a delay.
