### ISSUE TITLE
chef-provisioning should not be a dependency

### ISSUE THREAD

**Issue by albertsj1** [johnbellone/consul-cookbook#137]
For some reason, chef-provisioning has been added to metadata.rb as a dependency.  While I understand chef-provisioning is used for testing this cookbook, I don't see the need for it to be in metadata.rb.  If anything, it should be in the Gemfile.  Please remove this dep.

**Comment by johnbellone** [comment]
Removed in [this commit for 1.0.0](https://github.com/johnbellone/consul-cookbook/commit/28e88e6623be623648372deb90e4c4d0f4008523).

**Comment by albertsj1** [comment]
Thanks
