### ISSUE TITLE
`server` v `cluster` semantics unclear to new user / "Getting Started" under-discoverable

### ISSUE THREAD

**Issue by donaldguy** [johnbellone/consul-cookbook#149]
As I explained at length in #135 , I shot myself in the foot by missing the Getting Started section. I saw Usage, it only mentioned chef-provisioning which I didn't want to use (cause we autoscale) and by the time I was reading LWRP definitions, I assumed all that would follow was more of that (which I would look at more closely once I had a cluster running) and perhaps a "contributing" section.

Additionally, in the process of debugging I got as far as setting `bootstrap_expect` manually and finding that it wasn't getting written to my config. This is because I was using `server` rather than `cluster` for my service mode. I didn't understand the difference on account of being unaware of the getting started section.

As of 0.9.0, a user will likely figure out the semantics by the time they get a cluster working, but once Atlas autojoin is merged the failure to set `bootstrap_expect` with `server` is likely to confuse more users. (since Atlas will let `consul members` return correctly - but no leader will be elected).

**Comment by johnbellone** [comment]
I am closing this out because of impeding #126 landing on master.
