### ISSUE TITLE
Broken SysVinit script -- Consul fails to start on RHEL platforms (Amazon Linux, CentOS, etc.)

### ISSUE THREAD

**Issue by agperson** [johnbellone/consul-cookbook#150]
Standard "init" fails to start due to quoting of $CMD.  Removing quotation marks fixes issue:

```
[root@server1 consul.d]# service consul start
Starting consul
Running: /usr/bin/consul agent -config-dir /etc/consul.d
Unable to start consul, see /var/log/consul.log
```
Logfile is empty but in messages:
```
Mar 20 21:50:06 server1 consul: /etc/init.d/consul: line 46: /usr/bin/consul agent -config-dir /etc/consul.d: No such file or directory
```

After removing quotation marks:
```
[root@server1 consul.d]# service consul start
Starting consul
```

Change is: #115 (77b2fd90a24fd737528fa5a2da8f141a1a6b0d71 line 44)

**Comment by hatchetation** [comment]
This issue affects us as well on RHEL, this would seem to affect *all* platforms using SysVinit.  The fix @agperson mentions works well here, seems sane.

**Comment by agperson** [comment]
updated title.
