### ISSUE TITLE
Running default.rb recipe

### ISSUE THREAD

**Issue by rackerbenoit** [johnbellone/consul-cookbook#157]
file[/etc/consul.d/default.json] action create (up to date)
  * template[/etc/sysconfig/consul] action create (up to date)
  * template[/etc/init.d/consul] action create (up to date)
  * service[consul] action enable (up to date)
  * service[consul] action start

    ================================================================================
    Error executing action `start` on resource 'service[consul]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'

**Comment by rackerbenoit** [comment]
I should be able to just run this and have everything installed, yes?: chef-client -o "recipe[consul::install_source]"

**Comment by johnbellone** [comment]
What operating system and version are you using?

**Comment by rackerbenoit** [comment]
I am using CentOS 6.6 on an AWS EC2 node.

**Comment by krzysztofszarek** [comment]
I have the same issue on CentOS 6.6 on AWS.

**Comment by rackerbenoit** [comment]
Intersting....I haven't had a lot of time to look through the Cookbook but I feel like it should be a simple fix. Hopefully anyways

**Comment by rackerbenoit** [comment]
@johnbellone, any progress on this?

**Comment by agperson** [comment]
Isn't this just #150?

**Comment by rackerbenoit** [comment]
Not quite. When I run this command: chef-client -o "recipe[consul::install_source]"
The installation never happens and the error listed above is thrown.

**Comment by GonZo** [comment]
Hi, 
 I'm having the same problem running "CentOS release 6.6 (Final)"
:+1: 

Cheers

**Comment by rojomisin** [comment]
I have the same issue on aws and vagrant instances, I have tried using vagrant boxes 'chef/centos-6.6' and 'chef/centos-7.0'.  (I prefer centos66)
looks to be related to the go install 

```
==> default: [2015-05-04T21:27:17+00:00] INFO: directory[/opt/go/src/github.com/hashicorp] mode changed to 755
==> default: [2015-05-04T21:27:23+00:00] INFO: git[/opt/go/src/github.com/hashicorp/consul] cloning repo https://github.com/hashicorp/consul.git to /opt/go/src/github.com/hashicorp/consul
==> default: [2015-05-04T21:27:40+00:00] INFO: git[/opt/go/src/github.com/hashicorp/consul] checked out branch: master onto: deploy reference: 2af630987024eb097644efd30fd24d6a4a1a48c0
==> default: 
==> default: ================================================================================
==> default: Error executing action `run` on resource 'bash[/usr/local/go/bin/go get -v github.com/hashicorp/consul 2> >(grep -v '(download)$' > /var/chef/cache/github.com-hashicorp-consul)]'
==> default: ================================================================================
==> default: 
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '2'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150504-11930-ge5dvn" ----
==> default: STDOUT: 
==> default: STDERR: 
==> default: ---- End output of "bash"  "/tmp/chef-script20150504-11930-ge5dvn" ----
==> default: Ran "bash"  "/tmp/chef-script20150504-11930-ge5dvn" returned 2
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default: /tmp/vagrant-chef/8a58051761101d963b0e19a4a6162591/cookbooks/golang/providers/package.rb:14:in `block in class_from_file'
==> default: 

```

here's the full error output in a gist
https://gist.github.com/rojomisin/bffd4417019dbb30681d

**Comment by johnbellone** [comment]
I am closing this out because of impeding #126 landing on master. This is converging cleanly on EL6.6.
