### ISSUE TITLE
consul systemd hangs at 'create symlink at /etc/service/consul to /etc/sv/consul' on Centos70

### ISSUE THREAD

**Issue by rojomisin** [johnbellone/consul-cookbook#168]
I am trying to get consul to work on Centos70, which worked in Vagrant, so I packer'd up a centos7 ami and launched with `recipe[consul]` and custom json
```
    "consul": {
      "install_method": "binary",
      "init_style": "systemd"
    }
```
things seemed ok, but it just hangs endlessly

```
    * template[/etc/sv/consul/log/config] action create
      - create new file /etc/sv/consul/log/config
      - update content in file /etc/sv/consul/log/config from none to e3b0c4
      (no diff)
      - change mode from '' to '0644'
      - restore selinux security context
    * link[/etc/init.d/consul] action create
      - create symlink at /etc/init.d/consul to /sbin/sv
    - configure service runit_service[consul]
    * link[/etc/service/consul] action create
      - create symlink at /etc/service/consul to /etc/sv/consul
```

does anyone have a working combination of centos66 or centos7 + consul working?

**Comment by johnbellone** [comment]
The 1.0 release will support systemd/upstart/sysv through poise-service.

**Comment by johnbellone** [comment]
I am closing this out because of impeding #126 landing on master. The expectation here is that you'll be able to use the native pid managers as well as others such as supervisord/runit.
