### ISSUE TITLE
Error executing action `extract` on resource 'libarchive_file[consul.zip]'

### ISSUE THREAD

**Issue by jslusher** [johnbellone/consul-cookbook#170]
I'm still looking into what changed since I had this working last week. I'm getting this error now from the consul::install_binary recipe:
    uninitialized constant Archive::EXTRACT_OWNER

Initial googling shows that it's related to the ruby gem that unzips files (libarchive I suppose). I don't believe the version of that has changed, but I can't be certain just yet. I thought it merited an issue in this cookbook repo since it might happen to others. I'll add more info if I get it. If anyone has any suggestions, that would be great.

**Comment by dpkp** [comment]
consul-cookbook depends on libarchive cookbook, which is broken as of chef-dk v0.4

see https://github.com/reset/libarchive-cookbook/issues/9

**Comment by johnbellone** [comment]
Is this still an issue with ChefDK 0.6?

**Comment by johnbellone** [comment]
#169
