### ISSUE TITLE
Multiple checks for one service

### ISSUE THREAD

**Issue by csghuser** [johnbellone/consul-cookbook#173]
Hi,
Sorry if this is obvious and I have missed it. Is there a way to add a service with multiple checks, rather than just one?

If so, what is the syntax?

Thanks!

**Comment by zarry** [comment]
I was actually wondering about this as well.

**Comment by csghuser** [comment]
Looks like this is the pull request where the feature was added to consul:
https://github.com/hashicorp/consul/pull/591

**Comment by zarry** [comment]
@johnbellone Would you like some help implementing this on general road to 1.0.0 stuff?  I have a need for this feature and don't mind doing some of the lifting.  We have been getting a ton of mileage from all your leg work already and I don't mind helping out where I can.

Not sure what sort of timeline you are looking for but I can probably manage the time over the next couple weeks to knock it out.

**Comment by johnbellone** [comment]
@zarry Yes that'd be great. Take a look at the [develop branch](https://github.com/johnbellone/consul-cookbook/tree/develop). I need to test the HWRP thoroughly and document them.

**Comment by zarry** [comment]
@johnbellone Are you changing some of the terminology from the current version/state to what is in the develop branch?  Looks like consul_service is now used to actually define a consul instance and not represent a service in consul?  Would consul_definition be where we define services?  Looks not fully implemented(or just lacking documentation)?

What is the current state of the develop branch?

**Comment by zarry** [comment]
Never mind, thats what I get for quickly skimming it.  I see what is going on.  I should have some time in the next day or two to start playing around with the development branch.  If you could make sure anything you have locally is pushed that would be great.

Thanks!

**Comment by johnbellone** [comment]
Right now I need to thoroughly test that branch, but otherwise I am waiting to get some time this week or next to document the definition HWRP. It would be a huge help to do that!

There are no commits locally. Once the README is written I am going to cut a patch release with remaining changes for 0.10 and merge in 1.0.

**Comment by zarry** [comment]
Actually, as I dive in I still think consul_definition may have been missing some attributes. for_keeps is empty and we have no way of supplying a service or check definition json to the file system.  

Regardless, I will get some documentation around it and make any changes I think should be there to make it work as I would expect.  We can hash out any of the details or your idea of how it should look when I submit the PR.  (To be fair I don't have a ton of experience with HWRP so I may be missing a common pattern)

**Comment by johnbellone** [comment]
@zarry I'll tackle this during my train ride home tonight.

**Comment by zarry** [comment]
@johnbellone Thanks, I spent a little time with it and I think I got a little lost with the HWRP.  I don't think I fully groked your vision and I wasn't able to pick it up and finish it from there.  If you can get a little more documentation I can do some testing for you.

**Comment by johnbellone** [comment]
@zarry No worries. I really need to write up a lengthy blog post and more documentation here.
