### ISSUE TITLE
Question - How to do different configs on different servers

### ISSUE THREAD

**Issue by spuder** [johnbellone/consul-cookbook#177]
I'm trying to figure out how to use this cookbook to deploy different configs on different servers. 

I have
```
consul-server01
consul-server02
consul-server03
web01
database01
```

How can I make it so that the web servers and the database servers have different configs? 

I'm thinking I could do one of the following. None of which seems optimal. 

1. Create wrapper cookbooks for each server type, the cookbook manages `/etc/consul.d/web.conf` ect..
2. Create single cookbook with conditional statements that deploy different templates based on hostnames. 

Is there something that I am missing? Whats the best way to deploy different configs to different servers?

**Comment by johnbellone** [comment]
This may be easier with the develop branch. I am writing tests for it now
and hoping to have it ready to ship in a week or so.

You would use the new LWRP for different consul instances.

**Comment by tgwizard** [comment]
One simple way would be to create three chef roles: `consul-server`, `web`, and `database`. Each of these include a their own recipe in their runlist, e.g. `consul_server.rb`, `web.rb`, and `database.rb`. These recipes could be in separate cookbooks, or in one common cookbook, depending on your use-case. The recipes depend on the `consul` cookbook and uses its resources/providers/LWRP to define services and checks.

Then either your roles also includes the `consul` cookbook directly, or your recipes does. We have a separate `consul-agent` role with its own attributes (specifying consul version, user to run as, which datacenter to run in, and extra common configuration). All roles that use consul also include the `consul-agent` role.

**Comment by spuder** [comment]
Good idea, 

Can a runlist include just a single recipe? 

If so, I could make a `consul-agent` cookbook, where the `default` recipe is blank. 

```
consul-agent::default   #blank
consul-agent::webserver
consul-agent::database
```
Then I just include the specific recipies in the role. 

```json
{
  "run_list": [
    "recipe[mywebserver]",
    "recipe[consul-agent::webserver]",
    "role[mywebserver]"
  ]
}
```

**Comment by spuder** [comment]
^ This is what I ended up doing. It works well enough.
