### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by spuder** [johnbellone/consul-cookbook#184]
I'd really like to install consul on my windows web servers. 

Are there any plans to add windows support? 

I'm pretty new to chef, and I'm not a windows expert. I'm debating how big of a task this would be.

**Comment by aardestani** [comment]
start by looking at this
https://github.com/johnbellone/consul-cookbook/pull/154

you need to download the specific revision of this repo that supports windows and use chef to install and configure consul, have already tried this on chef 11.18.6 and windows 2012 standard x64
