### ISSUE TITLE
Release Tag for 0.10.0

### ISSUE THREAD

**Issue by arodd** [johnbellone/consul-cookbook#187]
Can you change the release tag to match the pattern? I can see us using this in the future to help constrain our cookbooks to a specific version when using this tool.  https://github.com/websterclay/knife-github-cookbooks

IE: KV in consul to represent community cookbook and currently desired push to chef.

cookbook: "git@github.com:johnbellone/consul-cookbook.git"
version: "v0.8.3"

1. make a new blank repository in the current directory
`git init`

2. add a remote
`git remote add origin git@github.com:johnbellone/consul-cookbook.git`
 
3. Fetch a commit (or branch or tag) of interest
  **Note: the full history of this commit will be retrieved
`git fetch origin v0.8.3`

4. reset this repository's master branch to the commit of interest
`git reset --hard FETCH_HEAD`

**Comment by arodd** [comment]
I now see that the v0.10.0 tag exists which I think as long as the tag exists it should likely be fine in my case.

**Comment by johnbellone** [comment]
I modified the release so that it points to v0.10.0.
