### ISSUE TITLE
chown resource executes every run, even when not changing anything

### ISSUE THREAD

**Issue by miketheman** [johnbellone/consul-cookbook#191]
We commonly see an execute resource updated every chef run, despite nothing being changed:
Example from our env:
```
- execute[chown -R root:root /mnt/consul] (consul::_service line 60)
- execute[chown -R root:root /etc/consul.d] (consul::_service line 60)
- execute[chown -R root:root /var/lib/consul] (consul::_service line 60)
```

This was introduced in #141 - [current source](https://github.com/johnbellone/consul-cookbook/blob/65bc614698e8d18153dc843cfd352da23af0aba2/recipes/service.rb#L62).

A better approach is to guard the resource and execute only if necessary, something like:
```ruby
execute "fixup consul #{dirname}" do
  command "chown -R #{consul_user}:#{consul_group} #{dirname}"
  only_if { Etc.getpwuid(File.stat(dirname).uid).name != "root" }
end
```

This is untested example code, based on conversations in mailing list and jira ticket tracker from 6 years ago, and the current conditional only applies to the uid, not gid. That should be an easy-enough fix.

Another method would be to use Ruby to get all subdirectories and create resources for each one, but that could lead to unexpected resource creation, if dirname has 10k subdirs - unlikely but possible.

I'd be happy to submit a PR for this, if you're interested in this approach.

/cc: @darron

**Comment by johnbellone** [comment]
This seems reasonable to me. Feel free to drop a PR and I'll cut another release prior to merging #126.
