### ISSUE TITLE
Kitchen tests failing on master (commit a8d3060)

### ISSUE THREAD

**Issue by gdavison** [johnbellone/consul-cookbook#194]
The existing tests on the master branch are not all passing for me.

None of the CentOS 7 tests pass, because the default interface is set to enp0s3 instead of eth0. Using a fresh copy of `opscode-centos-70`.

None of the runit tests pass. The error is `/etc/service/consul: unable to open supervise/ok: file does not exist`, though I can start the service manually using `sudo /usr/bin/sv restart /etc/service/consul`.

The source tests also fail trying to download git.

**Comment by johnbellone** [comment]
I am going to close this out. Proper testing and support will land for EL7 in #126.
