### ISSUE TITLE
Anything chef-brigade can do to help?

### ISSUE THREAD

**Issue by josephholsten** [johnbellone/consul-cookbook#197]
Is there anything @chef-brigade can do to help out? We're probably going to start using this in our infra, so we want to keep it awesome.

If you need any administrative help, want a slack channel, website, testing infra &c, just let us know. It doesn't need to have the brigade name anywhere on it.

**Comment by johnbellone** [comment]
@josephholsten Appreciate the request, but I think we're covered.
