### ISSUE TITLE
How to pass extra options since refactor?

### ISSUE THREAD

**Issue by scalp42** [johnbellone/consul-cookbook#209]
Hi @johnbellone 

Any clues on how to pass extra options for the agent?

I'm looking at [retry_join](http://www.consul.io/docs/agent/options.html#retry_join) for example, but not sure how to pass it in a wrapper cookbook, as the resource does not have it (https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_config.rb#L69).

Another example is the typo `recurser` in cookbook vs [recursor](http://www.consul.io/docs/agent/options.html#recursor) in the config resource. How can I correctly pass `recursor` instead of `recurser` ?

Would allowing a hash config make more sense instead of duplicating the agent config in the resource?

Thanks in advance

**Comment by scalp42** [comment]
I'm ending up with something like this:

```ruby
file node['wrapper']['config_path'] do
  owner node['consul']['service_user']
  group node['consul']['service_group']
  mode '644'
  content lazy { JSON.pretty_generate(node['wrapper']['config_settings'], quirks_mode: true) }
end

consul_service node['consul']['service_name'] do |r|
  user node['consul']['service_user']
  group node['consul']['service_group']
  version node['consul']['version']
  config_file node['gz-consul']['config_path']
  node['consul']['service'].each_pair { |k, v| r.send(k, v) }
  subscribes :restart, %|file[#{node['wrapper']['config_path']}|, :delayed
  action [:enable, :start]
end
```

**Comment by johnbellone** [comment]
I have a quick solution to this in the short term, but we should fix the bugs in the configuration. If there are any additional options added we should check against those. I'll have a change up in a little bit.

**Comment by scalp42** [comment]
One of the other workaround is to also drop a JSON in `config-dir` as it'll be merged with the `config-file` passed:

```
exec /usr/bin/env consul agent -config-file=/etc/consul.json -config-dir=/etc/consul
```

The later `-config-dir=/etc/consul` will override the defaults from the resource.
