### ISSUE TITLE
client config not being created

### ISSUE THREAD

**Issue by devilldog** [johnbellone/consul-cookbook#217]
I have added the following to my recipe, I also have consul in the run list (?) 
 ```chef 
node.default['consul']['config']['start_join'] = %w{10.10.xx.xx 10.10..xx.xx 10.10.xx.xx 10.10.xx.xx }
node.default['consul']['config']['client_addr'] = node['ipaddress']
#

consul_definition "epm_worspace_#{node['fqdn']}" do
   type 'service'
   parameters(http: 'http://10.109.xx.xx:9000/workspace/status',tags: %w{essabse}, address: node['fqdn'], port: 19000, interval: '30s')
   notifies :reload, 'consul_service[consul]', :delayed
 end
```

but the config that gets generated is 
```json
 {
  "data_dir": "/var/lib/consul",
  "client_addr": "0.0.0.0",
  "ports": {
    "dns": 8600,
    "http": 8500,
    "rpc": 8400,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
  "verify_incoming": false,
  "verify_outgoing": false
}
```

thanks !
Rob

**Comment by devilldog** [comment]
I will say the check definition gets created but the consul agent config is wrong and unable to reach the cluster

**Comment by ramonskie** [comment]
when i do the following in my wrapper cookbook

```
node.default['consul']['config']['start_join'] = %w{ 172.21.xx.xx 172.21.xx.xx 9 172.21.xx.xx }
include_recipe 'consul'
```
it sets consul in server mode for some strange reason

**Comment by gdavison** [comment]
This cookbook defaults to installing a server.

See line 80 in https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_config.rb#L80

**Comment by gdavison** [comment]
@devilldog are you still experiencing this? I can't reproduce it with v1.3.1.

You mention that you also have consul in the run-list. Is there maybe an ordering issue? Can you post your run-list?
