### ISSUE TITLE
Consul systemd unit should wait for network

### ISSUE THREAD

**Issue by eknudtson** [johnbellone/consul-cookbook#226]
The systemd unit for consul should have `After=network.target` in its `[Unit]` section.

**Comment by johnbellone** [comment]
This is a fair point, but I think its probably something we may want to push to the [Poise Service cookbook](https://github.com/poise/poise-service). I'll open a PR there.

**Comment by johnbellone** [comment]
Nevermind, I see where I need to dig into this.
