### ISSUE TITLE
Documentation for Data Bag Setup

### ISSUE THREAD

**Issue by wstaples** [johnbellone/consul-cookbook#238]
I'm looking for some documentation to setup the required databag. I'm starting this in test kitchen so I'm not sure if regular data bags will work. I looked at the chef-vault cookbook docs but did not see anything about test kitchen or chef solo. I'm assuming if this doesn't work with chef solo its not going to work with AWS Opsworks??

Also what about users who simply want to skip it?

**Comment by dsilverman-brightcove** [comment]
Please make the usage of Chef Vault optional.  There are many ways to pre-seed secrets, and Chef Vault is often not the right option.

**Comment by scalp42** [comment]
@dsilverman-brightcove :+1:

**Comment by johnbellone** [comment]
I am removing the management of TLS certificates with version 2.0. It has already landed in the [install-resource branch](https://github.com/johnbellone/consul-cookbook/tree/install-resource) and will be released in the next few days. I am just going through some integration tests. The plan is to have a separate example wrapper cookbook to draw from.
