### ISSUE TITLE
Unable to override databag attributes

### ISSUE THREAD

**Issue by vpack** [johnbellone/consul-cookbook#239]
I tried to override the databag attributes (to use 'consul-server' databag) but it gives an error - unable to access 'consul' databag.

Here is my wrapper code:
```
  node.default['consul']['bag_name'] = 'consul-server'
  node.default['consul']['bag_item'] = 'secrets'
```
It doesn't seem to use the config from file:/attributes/default.rb either.
```
  default['consul']['bag_name'] = 'secrets'
  default['consul']['bag_item'] = 'consul'
```

**Comment by johnbellone** [comment]
What does the wrapper cookbook look like? This should absolutely work.

**Comment by johnbellone** [comment]
I see the issue here.
