### ISSUE TITLE
Consul ACL custom resource

### ISSUE THREAD

**Issue by lmickh** [johnbellone/consul-cookbook#240]
Not sure where an ACL custom resource is at this point.  Looks like there were some PRs to add ACL resources, but they were closed for various reasons.  Is there currently work in progress?

**Comment by vancluever** [comment]
+1, we might need this shortly, would love to know either way.

**Comment by johnbellone** [comment]
I'm open to accepting custom resource for ACL.

**Comment by johnbellone** [comment]
The previous attempt in #220 seems to have halted due to a gem?
