### ISSUE TITLE
Basis for selinux set to disabled

### ISSUE THREAD

**Issue by ronlipke** [johnbellone/consul-cookbook#242]
What is the basis for setting selinux to disabled in this cookbook?  I see it changed from permissive sometime between version 1.2.0 and 1.3.0.
We have some compliance restrictions that require selinux and was surprised to see it outright disabled here.
Thanks!

**Comment by mdavis7771** [comment]
+1

**Comment by agperson** [comment]
But why is this cookbook managing SELinux at all?  I'm confused as to why it is in this purview at all.

**Comment by mdavis7771** [comment]
I agree with @agperson. As a security professional, having no documentation of this change and adding it to the run list could dramatically impact my security. SELinux should be managed be a separate wrapper cookbook.

**Comment by johnbellone** [comment]
@mdavis7771 It is a long story, but ultimately it is a relic from an incorrect generation of this cookbook about a year ago. I do not have a problem removing this cookbook touching SELinux at all.

**Comment by johnbellone** [comment]
I'll accept a PR here if either @mdavis7771 or @agperson is willing to do so. We'll need to increment the minor release.

**Comment by mdavis7771** [comment]
@johnbellone, Understood, I'll do a PR later this week.

**Comment by Ginja** [comment]
#256 should fulfill this.
