### ISSUE TITLE
retry_interval should be a string

### ISSUE THREAD

**Issue by Chili-Man** [johnbellone/consul-cookbook#244]
The consul agent expects the `retry_interval` setting to be a string, but the `consul_config` lwrp wants it to be an integer: https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_config.rb#L75

```
* 'retry_interval' expected type 'string', got unconvertible type 'float64'
==> Error decoding '/etc/consul.json': 1 error(s) decoding:
```

**Comment by johnbellone** [comment]
Do you mind submitting a PR?

**Comment by scalp42** [comment]
@Chili-Man @johnbellone https://github.com/johnbellone/consul-cookbook/pull/245
