### ISSUE TITLE
Updating consul version does not restart consul

### ISSUE THREAD

**Issue by joerocklin** [johnbellone/consul-cookbook#251]
Not sure if this is a bug for poise, libartifact, or the use of them both here. What I'm seeing is: when running the cookbooks and doing an upgrade from 0.5.2 -> 0.6.0 (binary install), the binary gets updated but the service isn't restarted. It looks like there's a subscription on config file changes, but there's no config file change in this process!

I looked to see if there was a convenient way to subscribe/notify on a binary update, but I'm not very familiar with poise or libartifact, and the fact that it's updating the binary inside an LWRP complicates things a bit.

**Comment by Ginja** [comment]
I noticed this as well.

+1

**Comment by johnbellone** [comment]
I have tracked this down with some of our other cookbooks. I'm going to test a fix.

**Comment by kamaradclimber** [comment]
hello @johnbellone,

do you need help for a fix on this issue?

**Comment by johnbellone** [comment]
Some help would definitely be appreciated!

**Comment by gdavison** [comment]
I've noticed recently that, at least on Windows, it's not restarting on config file changes, either. Not sure if this is related.

Steps:
1. Install
2. Consul starts
2. Tweak config attributes
3. Re-run chef
4. Doesn't restart

**Comment by scalp42** [comment]
Any chance to make the restart optional please?
