### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by ls12styler** [johnbellone/consul-cookbook#258]
Hi,

Just wondering what the sort of roadmap is for the next version?
(I'm wanting consul 0.6 ideally via a release version)

Thanks

**Comment by turkenh** [comment]
+1 on this.

**Comment by johnbellone** [comment]
I am trying to tackle [these issues](https://github.com/johnbellone/consul-cookbook/milestones/1.4) for the 1.4 release. I don't think its too much work, but definitely looking for some help cleaning up the queue!

**Comment by phs** [comment]
I don't suppose you'd cut a `1.3.2` in the mean time so we can get #234?

**Comment by johnbellone** [comment]
Let's see if we can knock out #217 and #235 first... any takers?

**Comment by johnbellone** [comment]
Just a quick recap - I'm waiting on #265 and #262 (to pin version) - then we're good to release. Thanks for the awesome work @legal90 and @Ginja!

**Comment by bigbam505** [comment]
Hey just wanted to check in on the status of the 1.4 Version release.  Trying to get our hands on that sweet sweet windows support :).  Awesome work thus far!

**Comment by johnbellone** [comment]
Released!
