### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by Ginja** [johnbellone/consul-cookbook#262]
I'm not sure if anyone else is noticing this, but I'm seeing this cookbook consistently apply at least 3 resources (on both Windows & Linux hosts):

![image](https://cloud.githubusercontent.com/assets/1631363/12467292/217f08f8-bf8f-11e5-837c-cfde35e206e1.png)

When I view what resources were changed in our monitoring tool, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1631363/12467329/5b445642-bf8f-11e5-8639-96a93ce40bce.png)

I'm wondering if this is because of Poise. I haven't done a deep-dive into this issue as I wanted to bring it up here in case this is to be expected.

**Comment by scalp42** [comment]
@Ginja unrelated but where is this UI from ?

**Comment by johnbellone** [comment]
We have noticed this recently while trying to fix some restart issues in other cookbooks. I think our initial thoughts led us to the [libartifact cookbook](https://github.com/johnbellone/libartifact-cookbook) or the [libarchive cookbook](https://github.com/reset/libarchive-cookbook).

**Comment by Ginja** [comment]
@johnbellone: I was thinking that too, but I'm seeing this even in the Windows provider (the pictures above are actually using it), which doesn't use libartifact or libarchive resources.

@scalp42 It's [the Foreman](https://github.com/theforeman/foreman). I have a cookbook to configure one into a reporting server for Chef that I'll release when it's ready for the public eye ;)

**Comment by johnbellone** [comment]
I was tinkering with the libarchive cookbook last night and narrowed it down there. Not sure about Windows. It looks like we have a few places this needs to be fixed.

**Comment by Ginja** [comment]
You're right, the inherent problem is in the libarchive cookbook, as it does no check on whether or not it should run. It looks like it's leaving that up to the cookbooks that use it. So I have a fix for libartifiact:

```ruby
# Lines 56 to 71
# https://github.com/johnbellone/libartifact-cookbook/blob/master/libraries/libartifact_file.rb#L54

          archive_path = ::File.join(Chef::Config[:file_cache_path], friendly_name)
          archive = remote_file new_resource.remote_url do
            path archive_path
            source new_resource.remote_url
            checksum new_resource.remote_checksum
            action :create_if_missing
            notifies :extract, "libarchive_file[#{archive_path}]"
          end

          libarchive_file archive.path do
            action :nothing
            extract_to new_resource.release_path
            extract_options new_resource.extract_options
            owner new_resource.owner
            group new_resource.group
          end
```

If that looks alright to you, @johnbellone, I'll submit a PR to your [libartifiact-cookbook](https://github.com/johnbellone/libartifact-cookbook). This unfortunately doesn't fix Windows, I'll work on that next.

**Comment by johnbellone** [comment]
Great work! Yes, please submit the PR :). 

Sent from my iPhone
JB
