### ISSUE TITLE
consul service user /bin/false shell ?

### ISSUE THREAD

**Issue by epcim** [johnbellone/consul-cookbook#271]
I have testes 1.4 version from master and found the service_user created "consul" is being OOTB created with /bin/false default shell. Which causes all scripted checks effectively silent.

`poise_service_user` doesn't have the "shell" attribute. So the only way to make the user with effective shell is to create him first. https://github.com/poise/poise-service#poise_service_user

As I am quite new with consul I am not about to post PR as this might be resolved multiple ways.

**Comment by johnbellone** [comment]
Which checks are failing?

**Comment by epcim** [comment]
I mean consul_definition, type=check. In other words any script execution: parameters(script:'xyz.sh'). As the "service consul user" don't have a proper shell configured.

I workaround it by: 
{{{
# change the user shell "so it may run scripts for checks"
user node['consul']['service_user'] do
  shell '/bin/bash'
  action :modify
end
}}}

**Comment by johnbellone** [comment]
Ah, interesting. It makes sense that this doesn't work just wonder why we never caught it before.

**Comment by johnbellone** [comment]
This was fixed in recent patch.
