### ISSUE TITLE
Windows Consul service does not start up

### ISSUE THREAD

**Issue by gdavison** [johnbellone/consul-cookbook#273]
The consul service expects its data directory to exist. This was recently removed, in commit aac210a, causing consul to fail on startup

**Comment by Ginja** [comment]
This was removed in response to this:

https://github.com/johnbellone/consul-cookbook/pull/259#issuecomment-176679581

I haven't seen the behaviour you've described, but I'm testing it now with Test Kitchen.

**Comment by Ginja** [comment]
Just verified that the data directory is being created. What does your run list look like? Could you send me the output of your failed run?

**Comment by Ginja** [comment]
Ah, I see why it worked for me now. In our wrapper cookbook I'm setting:

`node.default['consul']['config']['data_dir'] = join_path data_prefix, 'data'`

I think we should revert one of my changes in #259. I'm submitting another PR shortly. I'll add that in there.

**Comment by gdavison** [comment]
I've got at PR almost ready, with tests.

**Comment by Ginja** [comment]
@gdavison I have it included in #274. Please let me know if that works for you.

**Comment by gdavison** [comment]
Ah, didn't see that you have a PR, too.
