### ISSUE TITLE
Atlas Integration go away with v1?

### ISSUE THREAD

**Issue by jeremysmitherman** [johnbellone/consul-cookbook#277]
I'm looking through the history and it appears at one point in time, there was Atlas integration.  Has this gone away?  I can't find any modern documentation for the feature.

**Comment by johnbellone** [comment]
It has... but willing to a accept PR!

**Comment by fstradiotti** [comment]
+1 on this. Atlas integration variables used to be there and worked great...not sure why they have been removed. This cookbook is now broken in this state if you use consul together with atlas.

**Comment by jdoss** [comment]
Any chance on getting a minor point release with this addition?

**Comment by johnbellone** [comment]
@jdoss Yep, give me a few minutes.

**Comment by jdoss** [comment]
@johnbellone Thank you! http://i.imgur.com/WDRvQtW.gif
