### ISSUE TITLE
Service definition with an integrated check

### ISSUE THREAD

**Issue by fstradiotti** [johnbellone/consul-cookbook#280]
Hello, 
I've updated my wrapper cookbook to use the latest version of this consul-cookbook and noticed that the service/check definition has changed a lot. I am trying to create a service definition with an integrated health check but after reading through the documentation and doing trials and errors I can't seem to figure out how it's done. 

Previously I would have written something like this:
```
consul_service_def 'vault' do
  port 8200
  tags [
    'vault',
    'http'
  ]
  check(
    interval: '10s',
    http: 'http://127.0.0.1:8200/v1/sys/health',
    timeout: '5s'
  )
end
```

This is not allowed anymore so I tried doing it with the new type of consul_defitinion:
```
consul_definition 'vault' do
  type 'service'
  parameters(tags: 'vault, http', address: '127.0.0.1', port: 8200)
  notifies :reload, 'consul_service[consul]', :delayed
end

consul_definition 'vault_check' do
  type 'check'
  parameters(http: 'http://127.0.0.1:8200/v1/sys/health', interval: '10s', timeout: '5s')
  notifies :reload, 'consul_service[consul]', :delayed
end
```
This results in two independent resources which are not linked to each other. If I name both consul_definitions to "vault" then one will override the other one. 

How would I create a service definition with an integrated check like I did in my first example? Can someone point me in the right direction please? Thanks!

**Comment by johnbellone** [comment]
I think the only way to do this would be to update the `consul_definition` resource to have a parameter which accepts the parameters for the second resource.

**Comment by fstradiotti** [comment]
So that does this mean that there is no way to implement a previously available feature? 
Why did this useful feature get removed?

**Comment by gdavison** [comment]
This works for me:
```
consul_definition 'flipper-ui' do
  type 'service'
  parameters(
    port:  8000,
    check: {
      interval: '10s',
      http:     'http://localhost:8000'
    }
  )
  notifies :reload, 'consul_service[consul]', :delayed
end
```

**Comment by fstradiotti** [comment]
Thank you for the tip @gdavison, that was exactly what I was searching for. 

I have created a PR to update the readme with an example code snippet as I think this is useful information that should be added: https://github.com/johnbellone/consul-cookbook/pull/281

**Comment by johnbellone** [comment]
Thanks @fstradiotti and @gdavison !
