### ISSUE TITLE
Use 'system' attribute when adding consul user & group

### ISSUE THREAD

**Issue by leshik** [johnbellone/consul-cookbook#287]
Since consul is a system service, it's probably better to specify 'system' attribute to group and user resources: https://github.com/johnbellone/consul-cookbook/blob/master/recipes/default.rb#L35-L36
This can help distinguish them from those able to login. Also, since we have login shell provided, would be nice to specify existing $HOME location, e.g. /var/lib/consul.

**Comment by johnbellone** [comment]
The system attribute has been added to master and will be released as 2.0.
