### ISSUE TITLE
where does consul installed through this cookbook write its logs 

### ISSUE THREAD

**Issue by MichaelKueller** [johnbellone/consul-cookbook#290]
I'm running debian and I cannot find the log files created by consul. 
Also can the location be configured, as I would like to have the log in /var/log/consul.log?

**Comment by johnbellone** [comment]
What platform/version are you running?

**Comment by MichaelKueller** [comment]
I'm running debian 7.9

**Comment by johnbellone** [comment]
You can check /var/log/upstart/consul.log.

**Comment by MichaelKueller** [comment]
No, unfortunately not. The upstart directory does not exist under plain debian. As far as I know only older Ubuntu versions use upstart.

**Comment by johnbellone** [comment]
Is that version of Debian SysV?

**Comment by johnbellone** [comment]
This should be fixed in master. As long as there are no major problems I'll release as 2.0 by tomorrow afternoon.

**Comment by MichaelKueller** [comment]
That sounds great! thanks for the immediate response and help.
