### ISSUE TITLE
Key not found: "consul_0.6.3_linux_amd64"

### ISSUE THREAD

**Issue by MichaelKueller** [johnbellone/consul-cookbook#294]
When I try to run the latest master of this cookbook I get this error. It seems that this key is not provided in consul_installation_binary.rb. Only linux-x86_64 is listed there. It still worked in version 1.4.3, when these keys were part of the attributes file

**Comment by johnbellone** [comment]
What are you trying to do?

**Comment by MichaelKueller** [comment]
I'm trying to install consul though this cookbook on debian 7.

**Comment by johnbellone** [comment]
Yes, I guess I am confused with your error message. Would you be able to put the log in Gist? You should be able to run `kitchen converge default-debian-79` to get an instance with Consul installing and running.

**Comment by MichaelKueller** [comment]
I assume the problem is that this node attribute "node['kernel']['machine']" contains: amd64. But this is not  listed anymore. It basically is the same as x86_64. 

The error is: 
  ================================================================================
           Error executing action `enable` on resource 'consul_service[consul]'
           ================================================================================
           
           KeyError
           --------
           key not found: "consul_0.6.3_linux_amd64"

**Comment by johnbellone** [comment]
Please try again!

**Comment by MichaelKueller** [comment]
unfortunately the error still comes up. 

This is what I use in my kitchen file: 

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.9
    driver:
      box_check_update: true
      platform: debian
      provision_command:
        - apt-get update

**Comment by johnbellone** [comment]
Okay!

I'll give that a try this afternoon. 

Sent from my iPhone
JB

**Comment by MichaelKueller** [comment]
Oh, sorry for bothering you! I just noticed my tests were referencing an older commit of you github repository, which is why the errormessage did not make sense with your current code.
