### ISSUE TITLE
no more web ui?

### ISSUE THREAD

**Issue by wstaples** [johnbellone/consul-cookbook#297]
I have just upgraded to 2.0 and see that 
```
consul_ui 'consul-ui' do
	owner node['consul']['service_user']
	group node['consul']['service_group']
	version node['consul']['version']
end
```

is no longer valid. I see a [commit](https://github.com/johnbellone/consul-cookbook/commit/b25b15efe763e7f475abd390062b17e1f4d08765) that states the webui resource was dropped in favor of config. I have tried setting the node['consul']['config']['ui'] attribute to true and even setting the ui_dir attribute. They both wind up in the consul config file however the web_ui is not downloaded. Is installing the web_ui still supported?

**Comment by johnbellone** [comment]
I'll fix this in a little while. I have a change locally just testing.
