### ISSUE TITLE
Consul service should restart instead of reload

### ISSUE THREAD

**Issue by miroswan** [johnbellone/consul-cookbook#307]
If I make a change to a config, it doesn't show in the API or UI until I actually restart the service. Reload doesn't seem to suffice.

**Comment by wstaples** [comment]
Hi @miroswan,

Can you tell us what configuration change you are making that doesn't seem to reload? 
I assume you are reloading the service and not using the CLI `consul reload`
According to the [docs](https://www.consul.io/docs/agent/options.html#reloadable-configuration) These are the only re-loadable items

### Reloadable Configuration

Reloading configuration does not reload all configuration items. The items which are reloaded include:

-Log level
-Checks
-Services
-Watches
-HTTP Client Address
-Atlas Token
-Atlas Infrastructure
-Atlas Endpoint

**Comment by legal90** [comment]
@miroswan Automatic consul daemon restart could be really harmful. Please refer to the discussion https://github.com/johnbellone/consul-cookbook/issues/288
