### ISSUE TITLE
Implementing bootstrap-expect

### ISSUE THREAD

**Issue by kshep** [johnbellone/consul-cookbook#31]
Per the current Consul docs:

> The recommended way to bootstrap is to use the -bootstrap-expect configuration option. This options informs Consul of the expected number of server nodes, and automatically bootstraps when that many servers are available. To prevent inconsistencies and split-brain situations, all servers should specify the same value for -bootstrap-expect or specify no value at all. Any server that does not specify a value will not attempt to bootstrap the cluster.
>
> -- http://www.consul.io/docs/guides/bootstrapping.html

Should there be a new <code>['consul']['service_mode']</code> setting for bootstrap-expect?

I'd be happy to tackle this and submit a PR if it's not a high priority for anybody else.

**Comment by kainosnoema** [comment]
This looks resolved to me. Thanks!
