### ISSUE TITLE
Finding the Consul executable

### ISSUE THREAD

**Issue by gdavison** [johnbellone/consul-cookbook#311]
With the changes in version 2, the Consul executable will be at `/opt/consul/<version>/consul` if installed using `binary, `/usr/local/src/consul/bin/consul` if installed via git, or `/usr/local/bin/consul` in installed using a package manager . `/opt` is not typically in the `PATH`.

I have a downstream cookbook that needs to reference the Consul executable. I used to be able to reference it using `consul` and it would find it on the path. I could re-create the path to consul myself, but that requires knowledge of the internal workings of this cookbook, which could potentially change.

I'd suggest either symlinking all Consul executables to a single location, such as `/usr/local/bin`, or "publishing" the location using node attributes or the `run_state`.

Thoughts?

**Comment by johnbellone** [comment]
What does your wrapper cookbook look like? There are a few ways we could go about this. Adding in an optional symlink is okay, but not always preferable if there needs to be multiple versions.

**Comment by Ginja** [comment]
I always found managing symlinks for this type of stuff to be a pain in the providers. Since we're auto-generating the scripts that run these services (consul, vault, consul  template), we can just reference the direct path.

**Comment by johnbellone** [comment]
It is also worth nothing that you can grab the resource object and get the [path to the executable](https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_installation.rb#L26-L28). I *think* that this syntax is correct. 
```ruby
include_recipe 'consul::default'
consul = node.run_context.resource_collection.find('consul_installation[0.6.4]')
puts consul.consul_program
```

**Comment by gdavison** [comment]
Thanks, that does the trick! I didn't know you could do that. It doesn't appear to need to be in a ruby block, but I'll do some more testing.

It's actually an application cookbook for `consul-replicate`.
