### ISSUE TITLE
Question: How can a wrapper cookbook specify additional systemd options

### ISSUE THREAD

**Issue by kamaradclimber** [johnbellone/consul-cookbook#314]
On some setups, the LimitNOFILE option is required in the consul service definition.

Is it possible to add this option using the wrapper cookbook pattern?

So far, I've tried to specify attributes such as 
`default['consul']['service']['options']['template'] = 'consul-wrapper:mytemplate.erb'`
(and similar variation) without any luck.

**Comment by johnbellone** [comment]
Unfortunately I am not sure this is something that can currently be set right now using a node attribute. I'm going to have to think a little more about it, but you should be able to use the [poise_service_options](https://github.com/poise/poise-service#poise_service_options) resource in a wrapper cookbook. The block below should do what you're looking for:
```ruby
poise_service_options node['consul']['service_name'] do
  options :systemd, template: 'consul-wrapper:mytemplate.erb'
end
```

**Comment by kamaradclimber** [comment]
thanks I'll try that

**Comment by johnbellone** [comment]
This is probably something that we could expose using inversion options (similar to what we do with the download URL). This allows us to override in a policy or wrapper cookbook. You can see an example in our [Redis cookbook README](https://github.com/bloomberg/redis-cookbook#advanced-usage). Unfortunately the inversion attribute name is the name of the resource which in this cookbook's case is the service name (_consul_) and tends to make the node attributes confusing.

**Comment by kamaradclimber** [comment]
Unfortunately, adding the code you suggested does not change anything.

**Comment by kamaradclimber** [comment]
I've succeeded by monkey patching your provider in my wrapper cookbook

```
module ConsulCookbook
  module Provider
    class ConsulService < Chef::Provider

      alias_method :old_service_options, :service_options unless method_defined?(:old_service_options)

      def service_options(service)
        old_service_options(service)
        service.options(:systemd, template: 'consul-criteo:systemd.service.erb')
      end
    end
  end
end
```

but I've submitted a cleaner patch in #316 to make this available to everybody
