### ISSUE TITLE
translate_wan_addrs config option not implemented

### ISSUE THREAD

**Issue by jschnare** [johnbellone/consul-cookbook#317]
I believe [translate_wan_addrs](https://www.consul.io/docs/agent/options.html#translate_wan_addrs) was added in 0.6.4.  It is not listed in the consul_config library.  Trying to set it raises a NoMethodError.

If I'm reading the code right, a workaround would be to pass this key/value through `options` on the consul_config resource.  Is that correct?

**Comment by johnbellone** [comment]
Yes that's the right way. But we should really add it to the config. I'll keep this open as a reminder. PR is welcome!
