### ISSUE TITLE
Delay upstart `started` event until Consul is ready

### ISSUE THREAD

**Issue by gdavison** [johnbellone/consul-cookbook#318]
When Consul is started with upstart, upstart emits a `started` event once the service is launched, but it takes several seconds before it is ready to serve requests. If you have other services, such as consul-replicate, which depend on Consul, they can thrash before Consul is ready.

A stanza can be added to the Consul upstart config that would delay emitting the event until it is ready, or a similar stanza can be added to the upstart configs of any services that depend on Consul. See http://upstart.ubuntu.com/cookbook/#post-start

I think it would make sense to add it to this cookbook, so that it's handled in one place, and also because it signals that Consul is truly ready.

Thoughts?

**Comment by johnbellone** [comment]
This makes sense to me. It should be added as a separate template and we can add the override in service options (consul service resource).
