### ISSUE TITLE
Package custom matchers for testing using ChefSpec

### ISSUE THREAD

**Issue by WarFox** [johnbellone/consul-cookbook#329]
Firstly, let me thank @johnbellone for creating this cookbook and making it open source.

I have a small proposal.

It will be nice to have matchers for testing resources in this cookbook, so that developers can write tests around it.

https://github.com/sethvargo/chefspec#packaging-custom-matchers

If we provide a matcher like the following, 
```ruby
# libraries/matchers.rb

if defined?(ChefSpec)
  def create_consul_definition(resource_name)
    ChefSpec::Matchers::ResourceMatcher.new(:consul_definiton, :create, resource_name)
  end
```

then developers will be able to write tests like the following

```
    it 'should create consul definiton' do
      expect(chef_run).to create_consul_definition(service_name)
        .with_type('servicie')
    end
```

If you agree, with this proposal, I don't mind raising a pull-request for this

**Comment by johnbellone** [comment]
You should have matchers automatically since we use the [Poise library](https://github.com/poise/poise) is that not the case?

**Comment by WarFox** [comment]
Oh didn't know about that. Let me verify!

**Comment by WarFox** [comment]
You are right! Poise has provided matchers for resources. I wasn't looking in the right place.

I'm just needed the following matchers
- create_consul_installation
- create_consul_definition
- enable_consul_service
- create_consul_config

**Comment by WarFox** [comment]
Closing this issue, as matchers are already available. Thanks!
