### ISSUE TITLE
consul_service reload on Windows fails

### ISSUE THREAD

**Issue by anuriq** [johnbellone/consul-cookbook#334]
@Ginja @jirkafajfr 
Referring to https://github.com/johnbellone/consul-cookbook/pull/330

Check `cwd` parameter of execute block:

```
         * consul_service[consul] action reload
           * execute[Reload consul] action run

             ================================================================================
             Error executing action `run` on resource 'execute[Reload consul]'
             ================================================================================

             SystemCallError
             ---------------
             The directory name is invalid. - CreateProcessW

             Resource Declaration:
             ---------------------
             # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/consul/libraries/consul_service_windows.rb

       68:           execute 'Reload consul' do
       69:             command 'consul.exe reload'
       70:             cwd ::File.dirname(new_resource.program)
       71:             action :run
       72:           end
       73:         end

             Compiled Resource:
             ------------------
             # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/consul/libraries/consul_service_windows.rb:68:in `block in action_reload'

             execute("Reload consul") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "consul.exe reload"
        backup 5
        cwd "/usr/local/bin"
        returns 0
        declared_type :execute
        cookbook_name "mycookbook"
             end

             Platform:
             ---------
             i386-mingw32


           ================================================================================
           Error executing action `reload` on resource 'consul_service[consul]'
           ================================================================================

           SystemCallError
           ---------------
           execute[Reload consul] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/consul/libraries/consul_service_windows.rb line 68) had an error: SystemCallError: The directory name is invalid. - CreateProcessW

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/env-fdm-scep/recipes/default.rb

           142: consul_service 'consul' do
           143:   action :reload
           144: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/env-fdm-scep/recipes/default.rb:142:in `from_file'

           consul_service("consul") do
             action [:reload]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :consul_service
             cookbook_name "env-fdm-scep"
             recipe_name "default"
             program "/usr/local/bin/consul"
           end

           Platform:
           ---------
           i386-mingw32


       Running handlers:
       [2016-07-05T13:03:53+03:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-07-05T13:03:53+03:00] ERROR: Exception handlers complete
       Chef Client failed. 6 resources updated in 46 seconds
```

**Comment by anuriq** [comment]
on the first run, these lines are used and everything's ok
https://github.com/johnbellone/consul-cookbook/blob/38ad0942e76874924729e2b61d503537ed604028/libraries/consul_installation_binary.rb#L76-L77
but then, default value is in place
https://github.com/johnbellone/consul-cookbook/blob/38ad0942e76874924729e2b61d503537ed604028/libraries/consul_service.rb#L48

**Comment by jirkafajfr** [comment]
Hi,

are you sure that:
- ```consul::default``` is in your run list prior to resource definition which notifies restart (even in second run)?  [ln-74.](https://github.com/johnbellone/consul-cookbook/blob/38ad0942e76874924729e2b61d503537ed604028/recipes/default.rb#L74) sets ```consul_service.program``` to same value as ```consul_installation.consul_program```.
- aren't you defining own ```consul_service[consul]``` and not specifying program property? Notify  then doesn't know which resource should be executed (resource cloning).
- are you using binary installation? Other versions won't work since they don't provide proper ```consul_program``` for windows environments (but you would not pass even installation).

**Comment by jirkafajfr** [comment]
Hi @anuriq,

its actually visible in your log:
```
Resource Declaration:
---------------------
# In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/env-fdm-scep/recipes/default.rb

142: consul_service 'consul' do
143:   action :reload
144: end
```

You should not have two resources of same type which are sharing name (see [CHEF-3694](http://tickets.chef.io/browse/CHEF-3694). Since program property is not set in your definition it will use default and fail.

I don't think that you should reload config with each converge. But equivalent to your code would be
```
log 'reload consul' do
  notifies :reload, 'consul_service[consul]', :immediate
end
```

**Comment by anuriq** [comment]
Hi @jirkafajfr 
I provided wrong log. In this case i added consul_service explicitly.
I define consul_service['consul'] one time in a "base" cookbook with `action :nothing`. Than definitions notify it. I'll provide correct log, where no duplicate consul_service is defined and error is the same.

**Comment by jirkafajfr** [comment]
I think that's actually your problem. You should not define ```consul_service[consul]``` at all. It's already defined in [consul cookbook default recipe](https://github.com/johnbellone/consul-cookbook/blob/master/recipes/default.rb#L61) with proper parameters.

**Comment by anuriq** [comment]
we just have a really weird installation method for consul. you are right. thanks!
