### ISSUE TITLE
consul acl resource is not defaulting to configured consul url  and port

### ISSUE THREAD

**Issue by claudio-viola** [johnbellone/consul-cookbook#338]
https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_acl.rb#L20
it should be
'http://#{node['consul']['config']['client_addr']:#{node['consul']['config']['ports']['http']}'

**Comment by legal90** [comment]
Hi @claudio-viola 
Sorry, but it should not be so. `url` attribute of `consul_asc` resource defines the URL which will be used for _sending_ the request. 

However, both of `node['consul']['config']['client_addr']` and `node['consul']['config']['ports']['http']` define how the _local_ consul agent should be configured in case we want to set it up. Moreover, `node['consul']['config']['client_addr']` defaults to "0.0.0.0" which is OK for listening, but  couldn't be used as a targed address for sending reqests (as `consul_asc` needs).
