### ISSUE TITLE
Restart service instead reload as only few configurations are reloadble.

### ISSUE THREAD

**Issue by vijaybandari** [johnbellone/consul-cookbook#341]
Reload works only for few set of configurations as mentioned here. 
https://www.consul.io/docs/agent/options.html#reloadable-configuration

https://github.com/johnbellone/consul-cookbook/blob/master/recipes/default.rb#L45
It should be restart instead of reload.

**Comment by legal90** [comment]
Hi @vijaybandari 
That was done intentionally by https://github.com/johnbellone/consul-cookbook/commit/80f4a1ce4edb1638482e2391dabd1ba547ed7fad and https://github.com/johnbellone/consul-cookbook/pull/309
Please, refer to the discussion: https://github.com/johnbellone/consul-cookbook/issues/288 

TL;DR: Automatic restart of Consul servers could cause a cluster downtime when you run chef-client simultaneously. Also, if Consul version has been changed (upgrade scenario), then Consul servers should be restarted manually, according to [upgrade manual](https://www.consul.io/docs/upgrading.html)

**Comment by vijaybandari** [comment]
Thanks @legal90 , now it makes sense.
