### ISSUE TITLE
Installation archive URL should be configurable

### ISSUE THREAD

**Issue by drywheat** [johnbellone/consul-cookbook#342]
The archive URL is hardcoded to the value `"https://releases.hashicorp.com/consul/%{version}/%{basename}"` inside the `default_archive_url` class method defined by both the binary and webui installation resources.

Doesn't it make sense to move the base URL and checksums into attribute values so that cookbook consumers can cache copies of these packages where they see fit (e.g. S3, on-prem NAS, etc...)?

**Comment by stanchan** [comment]
I believe that this can be overridden by an inversion option. Not sure how it is being passed to the resource. Can anyone provide a sample of this?

**Comment by johnbellone** [comment]
```ruby
default['consul']['options']['archive_url'] = 'https://hashicorp.mirror.corporate.com/consul/%{version}/%{basename}'
```

**Comment by drywheat** [comment]
thank you.
