### ISSUE TITLE
Consul 0.7 is out!

### ISSUE THREAD

**Issue by Hoverbear** [johnbellone/consul-cookbook#343]
According to the [Hashicorp post](https://www.hashicorp.com/blog/consul-0-7.html) Consul 0.7 is now out.

[Downloads page](https://www.consul.io/downloads.html)

Changes required:
* [ ] Update the version string [here](https://github.com/johnbellone/consul-cookbook/blob/master/attributes/default.rb#L34)
* [ ] Add the checksums [here](https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_installation_binary.rb#L95-L192) from [here](https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_SHA256SUMS)
* [ ] ???

**Comment by Hoverbear** [comment]
#344 covers this issue.

**Comment by legal90** [comment]
Yeah, sure. 
Implemented by #344
