### ISSUE TITLE
Cut a new release of this cookbook?

### ISSUE THREAD

**Issue by jeffbyrnes** [johnbellone/consul-cookbook#347]
The last release of this cookbook was May 17, and quite a bit of good stuff has been added since then, as well as the release of Consul 0.7.0.

It’d be great to see a new version cut & pushed to Supermarket.

Notable changes:

* #315 
* #320 
* #321
* #344 

a plenty of fixes.

Perhaps v3.0.0, since the change in the Consul version is potentially breaking?

**Comment by johnbellone** [comment]
Why is the change breaking?

**Comment by jeffbyrnes** [comment]
Going along with Consul’s own versioning, a change from the 0.6.x series to 0.7.x is potentially breaking (as per SemVer), and, if an end-user of this cookbook has not set `node['consul']['version']` themselves, their systems will be upgraded to Consul 0.7.0, which may be undesirable.

As such, it seems polite & in-line with SemVer to bump this cookbook’s major version, for anyone whose wrapper is set like so: `depends 'consul', '~> 2.0'`, which is not uncommon.

**Comment by johnbellone** [comment]
Yes, but the version of the cookbook is independent of the Consul project. We've traditionally only bumped the major version of the cookbook when there is a backwards incompatibility in the cookbook's code itself (e.g. when we added the consul installation resource).

**Comment by jeffbyrnes** [comment]
I’m aware that it’s independent, but I think there’s a responsibility to the relationship between what version of Consul this cookbook installs by default, and what that might mean for an operator depending on this cookbook.

I would consider upgrading someone’s copy of Consul to be potentially breaking.

Is there some reason _not_ to bump the major number? Is there some negative I’m unaware of, other than operators needing to update their own wrappers?

**Comment by Hoverbear** [comment]
The last tagged release on Github was actually in February: https://github.com/johnbellone/consul-cookbook/releases

We're also quite interested in getting a new release cut.

**Comment by eyalzek** [comment]
+1

**Comment by Hoverbear** [comment]
@eyalzek Please don't use comments for +1ing things. Github specifically added a reaction flag for this purpose. If you want to stay up to date you can use the "Subscribe" button on the side.

**Comment by johnbellone** [comment]
The last release of the cookbook was 2.1.3 in May. I'm going to release the current master as 2.2.
