### ISSUE TITLE
Add support for Supervisord

### ISSUE THREAD

**Issue by mpsbauer** [johnbellone/consul-cookbook#363]
Looks like this only works with upstart, systemd, or sysV. Is there any hope of getting supervisor added to that list?

**Comment by johnbellone** [comment]
We are dependent on the upstream [poise-service cookbook](https://github.com/poise/poise-service) which currently does not have supervisord support. I know that its been on @coderanger backlog, but there is already support for [runit](https://github.com/poise/poise-service-runt) and [monit](https://github.com/poise/poise-monit).
