### ISSUE TITLE
Changelog doesn't mention v2.2.0, 2.1.3 or 2.1.1

### ISSUE THREAD

**Issue by tgwizard** [johnbellone/consul-cookbook#366]
The latest info in the Changelog is for v2.1.1: https://github.com/johnbellone/consul-cookbook/blob/b1c40f6e6ca92c44dbe3d5d6a2a58d8972952d1a/CHANGELOG.md#v211.

What has changed since then? Could we please update the changelog?

**Comment by tgwizard** [comment]
v2.2.0 seems to be the latest on chef supermarket: https://supermarket.chef.io/cookbooks/consul

**Comment by johnbellone** [comment]
I generated a new version using github changelog generator in #379. We are waiting for a few things prior to actually tagging/pushing.
