### ISSUE TITLE
Bind consul to a specific IP

### ISSUE THREAD

**Issue by raju-divakaran** [johnbellone/consul-cookbook#391]
Hello,

Recently we enabled docker-engine on a server where we are having consul agent also running. Soon after starting docker-engine, as we know the docker0 ( default bridge n/w ) is enabled. This results in consul not getting started, as it complains there are multiple internal IPs.

Can we please incorporate a way to bind consul agent to an IP if needed by including that option in the systemd file.

Thanks

**Comment by legal90** [comment]
Hi @raju-divakaran 
You can set any consul configuration option in the attribute, like this:
```
node.set['consul']['config'][OPT_NAME] = OPT_VALUE
```
In particular, for (bind_addr)[https://www.consul.io/docs/agent/options.html#bind_addr] it will be:
```
node.set['consul']['config']['bind_addr'] = "10.10.20.30"
```

Being passed to `consul_config` resource, these options will be rendered in `/etc/consul/consul.json` and parsed by the consul daemon after restart.
https://github.com/johnbellone/consul-cookbook/blob/master/recipes/default.rb#L43

**Comment by legal90** [comment]
I hope my comment above helps. 
Closing this issue.

**Comment by raju-divakaran** [comment]
Yes, I don't know how I missed that option. Thanks much!
