### ISSUE TITLE
Can't use the cookbook with Chef 11 because of firewall cookbook

### ISSUE THREAD

**Issue by barrowkwan** [johnbellone/consul-cookbook#392]
Hi,
  I am trying to use the cookbook Chef11 but got error with firewall cookbook because firewall cookbook 2.0.0 and above can only be used with Chef 12.  I wonder if consul 2.0 and above has to use firewall cookbook 2.0.0 or can use firewall cookbook with an earlier version?

**Comment by legal90** [comment]
IMO, I would remove "firewall" dependency from the cookbook (and the related block from the "default" recipe). That is an important thing, but is really specific and depends on the platform and the concrete use case, so it's better to handle it in a wrapper cookbook. 

@johnbellone, what do you think about this?

**Comment by johnbellone** [comment]
I agree with @legal90 - this should be managed inside of a wrapper such as [consul-cluster cookbook](https://github.com/bloomberg/consul-cluster-cookbook). But I want to stress that outside of this, @barrowkwan should note that Chef 11 is not supported by this cookbook. It may work, but that client version is very old.

**Comment by johnbellone** [comment]
This also constitutes a major version change.
