### ISSUE TITLE
When service_user is root and config user is consul, cookbook fails

### ISSUE THREAD

**Issue by jasonmcintosh** [johnbellone/consul-cookbook#405]
Consul 2.3.0 fails if the service_user is root, and the config user isn't set or is set to consul.  This causes the poise user to not be created, causing directory configuration to fail.  This is primarily when migrating from a 2.1.3 to 2.3.0 release. A few possible fixes off top of head...

Change default recipe so it'll create the user if either is false.
-----
  not_if { node['consul']['service_user'] == 'root' }
to be
  not_if { node['consul']['service_user'] == 'root' } and { node['consul']['config']['owner'] == 'root' }

Default config user to the service user
-----
Change attributes file to do:
default['consul']['config']['owner'] = default['consul']['service_user'] or similar.

**Comment by legal90** [comment]
https://github.com/johnbellone/consul-cookbook/pull/446 will fix that issue. 
A node attribute `['consul']['config']['owner']` will not be defined, so the dafault owner of Consul config will be a value of the node attribute `['consul']['service_user']` (which is "root" in your case).

https://github.com/johnbellone/consul-cookbook/blob/eebc1299cefb6d766218904ea372566cc84bf373/libraries/consul_config.rb#L23
