### ISSUE TITLE
UI support is not available

### ISSUE THREAD

**Issue by raju-divakaran** [johnbellone/consul-cookbook#409]
Hello,

Did we remove UI support from consul cookbook !?

Thanks

**Comment by jasonmcintosh** [comment]
Note, in the latest consul release, UI is there as a configuration option and not a separate deployment.  Consul itself still supports the old UI directory stuff, but you shouldn't need it.  

Looking, the cookbook no longer supports the old installation of the UI as a separate thing.
https://github.com/johnbellone/consul-cookbook/commit/9cd80b991f73ea15e1b19be926186743cb52a8ac

I'd say the cookbook probably should have left it in there for people who still used it, but I'd say you really really should update consul to the latest releases and remove the ui_dir config.

**Comment by legal90** [comment]
The details are here: https://github.com/johnbellone/consul-cookbook/pull/396
Disclaimer: yes, we removed it in the scope of the upcoming major version bump (v3.0.0)
