### ISSUE TITLE
Error message when running the server enable action on windows

### ISSUE THREAD

**Issue by brentm5** [johnbellone/consul-cookbook#436]
We are using a relatively older version of this cookbook (1.4.3) and today we started seeing an error which was really vague.  Ended up tracking it down to the [new version of nssm](https://github.com/dhoer/chef-nssm/releases/tag/v3.0.0).  It might make sense to actually lock this cookbook down to at least be `~> 2.0`. I am not sure if any other versions were affected by this as well however.

```
==============================================================
           Error executing action `enable` on resource 'consul_service[consul]'
==============================================================
           ArgumentError
           -------------
           wrong number of arguments (1 for 0)

```

**Comment by legal90** [comment]
@brentm5 Have you tried the latest state of `consul` cookbook from master branch? 
It should be fixed by https://github.com/johnbellone/consul-cookbook/pull/422 (not released yet)

**Comment by brentm5** [comment]
Nope, but if that solves the issue its good enough for me.  I just didn't see a fix anywhere.  Ill go ahead and close out my PR as well.
