### ISSUE TITLE
Bump supermarket cookbook version

### ISSUE THREAD

**Issue by davidsayers** [johnbellone/consul-cookbook#439]
Hi,

Would it be possible to upload a new version of this cookbook to the supermarket? There have been a lot of changes and I would rather not pull it directly from the repo.

David

**Comment by MichaelKueller** [comment]
Hey, I believe the title of this Issue is misleading, as you are asking for the version to be bumped rather than a new cookbook to be created.

**Comment by davidsayers** [comment]
Yeah, that's what I meant 😄

**Comment by jmauro** [comment]
+1
We really need some bugfixe.

Thx

**Comment by legal90** [comment]
Done. Finally, v3.0.0 is released and published on Supermarket.
Changelog: https://github.com/johnbellone/consul-cookbook/blob/f2e9e53a487431d10cc2500ed67166ccbf8a5c2a/CHANGELOG.md#v300-2017-06-11
