### ISSUE TITLE
windows service config file/dir paths not escaped with quotes in NSSM config

### ISSUE THREAD

**Issue by pjjohnstone** [johnbellone/consul-cookbook#448]
Command block from helpers.rb:
```
def command(config_file, config_dir)
      if windows?
        %(agent -config-file="""#{config_file}""" -config-dir="""#{config_dir}""")
      else
        "/usr/local/bin/consul agent -config-file=#{config_file} -config-dir=#{config_dir}"
      end
    end
```

But the resulting reg entry in the consul service hive is:
`agent -config-file=C:\Program Files\consul\consul.json -config-dir=C:\Program Files\consul\conf.d`

Which causes the following startup/restart error:
`Error reading 'C:\Program': open C:\Program: The system cannot find the file specified.`

Using latest master branch from repo NOT the supermarket cookbook.

**Comment by legal90** [comment]
Ping @Ginja. Could you please take a look at this issue? How does it work for you?

**Comment by pjjohnstone** [comment]
I can no longer reproduce this, no idea what was going on.

**Comment by knightorc** [comment]
@pjjohnstone   I hit the same issue. It depended on which version of nssm.exe was on your system. I've tweaked our local copy of this cookbook so we can support nssm cookbook > 4.0

@Ginja I was going to issue a PR to summit my tweaks after I'd tested all use cases.
