### ISSUE TITLE
Restart consul service after installation

### ISSUE THREAD

**Issue by maxnasonov** [johnbellone/consul-cookbook#450]
Currently it doesn't seem that the service is restarted after installation. Is it done on purpose (e.g. not to break a cluster)? Is it worth to have an option (as a parameter) to restart the service?

I've verified on 2.3.0 but 3.0.0's code looks the same.

**Comment by georgiou** [comment]
Looking at the update from 2.3.0 to 3.0.0 I see a service reload but since the systemd service file has an `ExecReload=/bin/kill -HUP $MAINPID` it doesn't switch to the new version

**Comment by legal90** [comment]
Hi @maxnasonov,
Yes, this cookbook's recipes don't trigger a consul service restart. You are right - it was done intentionally, in order not to break a cluster on the version upgrade:
https://github.com/johnbellone/consul-cookbook/issues/288

But you can try to use that trick, allowing to override any parameter of the resource defined in another recipe:
```ruby
include_recipe "consul::default"

r = resources(:consul_installation => node['consul']['version'])
r.notifies :restart, "consul_service[#{service_name}]"
```
