### ISSUE TITLE
Code coverage values are inconsistent and blocking PR to fix 3.0 for Windows

### ISSUE THREAD

**Issue by gdavison** [johnbellone/consul-cookbook#453]
I recently submitted PR #452, and it's blocked due to code coverage. I added tests to the cookbook, so this seemed weird.

The coverage report shows no coverage for actions on `consul_service_windows` that are definitely tested.

I then ran the tests locally to look at the coverage report, and the values reported changed from one run to the next with no code changes! (Note that the files change places in the list as well)

<img width="569" alt="screen shot 2017-07-12 at 09 33 06" src="https://user-images.githubusercontent.com/1148298/28128841-0587b960-66e6-11e7-9966-20f245501104.png">
<img width="763" alt="screen shot 2017-07-12 at 09 33 48" src="https://user-images.githubusercontent.com/1148298/28128843-05a52e50-66e6-11e7-9a27-d5cf955b4b1b.png">
<img width="765" alt="screen shot 2017-07-12 at 09 34 29" src="https://user-images.githubusercontent.com/1148298/28128842-05a37f10-66e6-11e7-874b-4722a1314bd5.png">

**Comment by legal90** [comment]
@johnbellone I would suggest disabling CodeCoverage integration for that repo until we got anybody who will be ready to bring everything to green and maintain this cookbook actively.

**Comment by johnbellone** [comment]
This has been disabled.
