### ISSUE TITLE
Repo metadata.rb says 3.0.0, but current files aren't tagged for 3.0.0 in git

### ISSUE THREAD

**Issue by northrup** [johnbellone/consul-cookbook#463]
The Chef Supermarket uses the repo tags for versioning and not just the metadata.rb, and what you have tagged as 3.0.0 is no longer consistent or fresh with that's in the repo with the metadata.rb of 3.0.0.

This manifests itself when using Consul 9.0 and wanting to use `enable_script_checks`, which is in the current attributes of the library, but not in the tagged v3.0.0 version.

Could we either get the tag updated, or cut a v3.0.1 version?

**Comment by eknudtson** [comment]
We're pointing our Berksfile entry for this cookbook at git vs the chef supermarket because of this.

**Comment by northrup** [comment]
@johnbellone not to be a pain, but can we get some update on this?

**Comment by johnbellone** [comment]
This should have been updated with the latest release. As of right now my release procedure is running `stove` which cuts a tag and pushes to the repository.
