### ISSUE TITLE
client_addr not included in configuration file

### ISSUE THREAD

**Issue by dpetzel** [johnbellone/consul-cookbook#73]
This is related to https://github.com/johnbellone/consul-cookbook/issues/72, but is a slightly different issue so want to treated it as such.

Based on the [documentation](https://consul.io/docs/agent/options.html#_client) the `client_addr` configuration element is what controls what IP's the service will bind to. When not set this defaults to 127.0.0.1. manually adding this element to the json configuration and restarting the service shows this to be the case.

I think the `client_addr` attribute needs to get added to the copy param in order to have the service listening on all available interfaces. Setting the `bind_addr` doesn't result in the service listening on anything except 127.0.0.1

**Comment by dontrebootme** [comment]
Running into this same issue. I vote for having the conditional for the ui removed from accepting client_addr or being reworked as well.

**Comment by johnbellone** [comment]
I am closing this out because of impeding #126 landing on master.
