### ISSUE TITLE
Wrong user used for services when using upstart

### ISSUE THREAD

**Issue by memelet** [johnbellone/consul-cookbook#96]
When the init_style is runit no user is created. But then when any of resources are used (ie, consul_service_def) they try to use node['consul']['service_user'] (== "consul").

**Comment by memelet** [comment]
Sorry, kind of lost track here. I have been using init_style=init but with this recipe (using 0.6.0):

```# This is to work around https://github.com/johnbellone/consul-cookbook/issues/96

user "consul service user: #{node['consul']['service_user']}" do
  username node[:consul][:service_user]
  home '/dev/null'
  shell '/bin/false'
  comment 'consul service user'
end

group "consul service group: #{node[:consul][:service_group]}" do
  group_name node[:consul][:service_group]
  members node[:consul][:service_user]
  append true
end
```

Next time I work on this wrapper I will test without creating the user.

**Comment by donaldguy** [comment]
@johnbellone This does not work, for wrapper cookbooks at least. `init_style` isn't set to `runit` until after compile of the cookbook, by which the user and group are already hardcoded as root on both node and in recipe variables

I am (working on) working around by using a chef-sugar `compile_time` block, but the better option might be to do the conditional evaluation in a `ruby_block` resource at runtime and user lazy attributes, OR just go all the way to LWRP territory

**Comment by dpkp** [comment]
Fixed in 0.7.0?

**Comment by johnbellone** [comment]
I'll wrap this up with the 1.0 release.

**Comment by johnbellone** [comment]
I am closing this out because of impeding #126 landing on master.
